name: Release

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:

  publish:

    name: Build & Publish Packages

    runs-on: windows-latest  

    environment:
      name: production

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Docker login
          run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Images
        run: |
          docker build --pull -f Dockerfile.linux-x64 -t genhttp/gateway:linux-x64 .
          docker build --pull -f Dockerfile.linux-arm32 -t genhttp/gateway:linux-arm32 .
          docker build --pull -f Dockerfile.linux-arm64 -t genhttp/gateway:linux-arm64 .
          docker build --pull -f Dockerfile.windows-x64 -t genhttp/gateway:windows-x64 .

      - name: Push Images
        run: |
          docker push genhttp/gateway:linux-x64
          docker push genhttp/gateway:linux-arm32
          docker push genhttp/gateway:linux-arm64
          docker push genhttp/gateway:windows-x64

      - name: Push Multi
        run: |
          docker manifest create --amend genhttp/gateway:latest genhttp/gateway:linux-x64 genhttp/gateway:linux-arm32 genhttp/gateway:linux-arm64 genhttp/gateway:windows-x64
          docker manifest push --purge genhttp/gateway:latest